#+title: 1366. Rank Teams by Votes
#+author: nshan651
#+options: tex:t toc:nil
#+startup: inlineimages latexpreview

https://leetcode.com/problems/rank-teams-by-votes/

In a special ranking system, each voter gives a rank from highest to lowest to all teams participating in the competition.

The ordering of teams is decided by who received the most position-one votes. If two or more teams tie in the first position, we consider the second position to resolve the conflict, if they tie again, we continue this process until the ties are resolved. If two or more teams are still tied after considering all positions, we rank them alphabetically based on their team letter.

You are given an array of strings votes which is the votes of all voters in the ranking systems. Sort all teams according to the ranking system described above.

Return a string of all teams sorted by the ranking system.

* Examples

** Example 1

#+begin_example
Input: votes = ["ABC","ACB","ABC","ACB","ACB"]
Output: "ACB"
Explanation:
Team A was ranked first place by 5 voters. No other team was voted as first place, so team A is the first team.
Team B was ranked second by 2 voters and ranked third by 3 voters.
Team C was ranked second by 3 voters and ranked third by 2 voters.
As most of the voters ranked C second, team C is the second team, and team B is the third.
#+end_example

** Example 2

#+begin_example
Input: votes = ["WXYZ","XYZW"]
Output: "XWYZ"
Explanation:
X is the winner due to the tie-breaking rule. X has the same votes as W for the first position, but X has one vote in the second position, while W does not have any votes in the second position.
#+end_example

** Example 3

#+begin_example
Input: votes = ["ZMNAGUEDSJYLBOPHRQICWFXTVK"]
Output: "ZMNAGUEDSJYLBOPHRQICWFXTVK"
Explanation: Only one voter, so their votes are used for the ranking.
#+end_example

* Constraints:
- $$1 <= votes.length <= 1000$$
- $$1 <= votes[i].length <= 26$$
- $$votes[i].length == votes[j].length$$ for $$0 <= i, j < votes.length$$
- votes[i][j] is an English uppercase letter.
- All characters of votes[i] are unique.
- All the characters that occur in votes[0] also occur in votes[j] where $$1 <= j < votes.length$$

*  Solution

#+begin_src C++ :includes <iostream> :flags -I./src/util -std=c++20 :tangle src/1366-rank-teams-by-votes.cpp
  #include <algorithm>
  #include <vector>
  #include <string>

  class Solution {
  public:

      std::string rankTeams(std::vector<std::string>& votes)
      {
        int numCandidates =  votes[0].size();
        std::string res(votes[0]);
        std::vector<std::vector<int>> rankings(numCandidates, std::vector<int>(26, 0));

        // First, populate the initial rankings
        for (auto& ballot : votes)
          for (int i = 0; i < numCandidates; ++i)
            rankings[i][ballot[i] - 'A']++;

        std::sort(res.begin(), res.end(), [&](char a, char b)
        {
          for (auto& ranking : rankings)
            // Sort lexographically if the candidates are the same.
            if (ranking[a - 'A'] != ranking[b - 'A'])
              return ranking[a - 'A'] > ranking[b - 'A'];
          // Otherwise, sort by the greatest number of first-choice votes.
          return a < b;
        });
        return res;
      }
  };

    int main()
    {
      Solution s1;

      std::vector<std::string> votes = {"ABC","ACB","ABC","ACB","ACB"};
      auto res = s1.rankTeams(votes);
      std::cout << res << std::endl;

      return 0;
    }
#+end_src

#+RESULTS:
: ACB
